### ISSUE TITLE
error "Cannot Find Sunrise!"

### ISSUE THREAD

**Issue by glafir** [rbur004/sunriseset#2]
rails - 3.2.21
ruby - 2.2.2

My SunRise
sr = SunRiseSet.new(DateTime.current, 53.4564,138.8954).sunrise.to_s(:time)

I get error in this string.
"Cannot Find Sunrise!"

Its work tree day ago. I do nothing. I restarted nginx+unicorn.

**Comment by rbur004** [comment]
That doesn't look to be far enough North to not have a sun rise. Must be a bug. 

This message is for places above the Arctic circle, or below the Antarctic circle, where they can have no sunrise or sunset during a day.

**Comment by rbur004** [comment]
Looks date related
puts SunRiseSet.new(DateTime.now - 4 , 53.4564,138.8954) fails
puts SunRiseSet.new(DateTime.now - 5 , 53.4564,138.8954) works

**Comment by rbur004** [comment]
It was a silly bug. I calculate sunrise and sunset, but also the civil, naval and astronomical twilight values. It was the astronomical twilight calculation that were failing, as at 53.5 degrees, at this time of year, the sun never gets low enough. The sunrise and sunset values where being calculated correctly.

I will create a new gem, which returns nil for the Astro, Naval and Civil times, if the location is too far north.

**Comment by rbur004** [comment]
Ok, update the gem to 0.9.2 and it should work.  
Nb. it is now possible to get nil values for Civil, Naval and Astronomical twilight, if they don't fall on the same day as the sunrise or sunset.

**Comment by glafir** [comment]
if latitude > 50, I get this error:

wrong number of arguments (3 for 1)

**Comment by glafir** [comment]
Is it possible to move from the calculations "http://suncalc.net/"?
Thi is a library of sunCaclulation
http://suncalc.net/scripts/suncalc.js
I do not use JS, because it is a problem with TimeZone in JS. The data of sunrise, sunset, sunposition, etc are calculated relatively by client-brouser. Change timezone in JS is not help. I want calculated the "sun data" relatively by my server.

**Comment by rbur004** [comment]
On 25/05/15 8:25 pm, Glafir wrote:
>
> Is it possible to move from the calculations "http://suncalc.net/"?
> Thi is a library of sunCaclulation
> http://suncalc.net/scripts/suncalc.js
> I do not use JS, because it is a problem with TimeZone in JS. The data 
> of sunrise, sunset, sunposition, etc are calculated relatively by 
> client-brouser. Change timezone in JS is not help. I want calculated 
> the "sun data" relatively by my server.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rbur004/sunriseset/issues/2#issuecomment-105163700>.
>
I'm guessing this should be directed to the maintainer of another 
package. I look after the sun calculation gem, which is obviously being 
included in the package you are using.


-- 
--
Rob Burrowes                    Ph:   +64 9 923 2308 (Internal 82308)
System Lead, NeSI Auckland      Cell: +64 27 4731856 (internal 64209)
Research Data Services Technical Lead
Centre for eResearch
The University of Auckland
Private Bag 92019               http://www.sit.auckland.ac.nz/~rob
Auckland Mail Centre            http://www.burrowes.org/
Auckland 1142                   http://www.wikarekare.org/
NEW ZEALAND

**Comment by rbur004** [comment]
On 25/05/15 8:09 pm, Glafir wrote:
>
> if latitude > 50, I get this error:
>
> wrong number of arguments (3 for 1)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rbur004/sunriseset/issues/2#issuecomment-105160801>.
>
This is odd, as no calls to methods were altered. The fix was to change 
the check for failure to find sunrise/sunset to only check the sunrise 
and sunset values not being found, and ignore errors in finding the 
twilight times.  This does mean that the twilight values could be nil, 
which might cause other errors, if nil were called, when a Time was 
expected.

The tests I run, do come back with sensible values, and no exception.

puts SunRiseSet.new(DateTime.now  , 53.5, 138.9)
produces:

Astro Twilight Not Found
Naval Twilight 04:27:21 26-05
Civil Twilight 05:40:46 26-05
Sun Rises 06:28:44 26-05
Solar noon  14:41:22 26-05
Sun Sets 22:55:00 26-05
End of Civil Twilight  23:43:16 26-05
Naval Twilight 00:57:46 27-05
Astro Twilight Not Found
####


-- 
--
Rob Burrowes                    Ph:   +64 9 923 2308 (Internal 82308)
System Lead, NeSI Auckland      Cell: +64 27 4731856 (internal 64209)
Research Data Services Technical Lead
Centre for eResearch
The University of Auckland
Private Bag 92019               http://www.sit.auckland.ac.nz/~rob
Auckland Mail Centre            http://www.burrowes.org/
Auckland 1142                   http://www.wikarekare.org/
NEW ZEALAND

**Comment by glafir** [comment]
wrong number of arguments (3 for 1)

@airport.latitude = 71.9283
@airport.longitude = 114.0800
sr = SunRiseSet.new(DateTime.current.in_time_zone(@airport.time_zone), @airport.latitude.to_f, @airport.longitude.to_f).sunrise.in_time_zone(@airport.time_zone).to_s(:time)
